CREATE TABLE Literature (
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	LiteratureName VARCHAR(40) NOT NULL,
	Picture VARBINARY(MAX) NULL,
	DisciplineId INT NULL
);

CREATE TABLE Discipline (
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	DisciplineName VARCHAR(40) NOT NULL,
	Course INT NOT NULL
);